GET http://localhost:8080/

###

GET http://localhost:8080/api/usuarios

###

POST http://localhost:8080/api/usuarios
Content-Type: application/json

{
    "email": "newton@gmail.com",
    "senha": "senha"
}

###

PUT http://localhost:8080/api/usuarios?id=15898ce2-d7f9-492f-a4f4-2c56aeb571a3
Content-Type: application/json

{
    "titulo": "Teste",
    "texto": "Preto"
}

###
DELETE http://localhost:8080/api/usuarios?id=4

###

POST http://localhost:8080/api/usuarios/login
Content-Type: application/json

{
    "email": "newton@gmail.com",
    "senha": "senha"
}